<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Softeq.XToolkit.Common\Softeq.XToolkit.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.6.2.1" />
  </ItemGroup>

</Project>