parameters: # defaults for any parameters that aren't specified
  SolutionPath: ''

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    # setup env
    - task: UseDotNet@2
      displayName: 'Use .Net Core sdk'
      inputs:
        version: $(DOTNET_SDK_VERSION)
    - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
      displayName: Switch to the latest Xamarin SDK
    - bash: |
        sw_vers
        ls /Applications
        echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app
        sudo xcode-select -s /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      displayName: Switch to the latest Xcode
    # restore, build
    - script: 'msbuild ${{ parameters.SolutionPath }} -r /p:Configuration="$(BuildConfiguration)" /p:Platform="Any CPU"'
      displayName: Build Solution
    - task: DotNetCoreCLI@2
      displayName: Run Tests
      inputs:
        command: test
        projects: |
          **/*.Tests.csproj
          !**/*.iOS.Tests.csproj
          !**/*.Droid.Tests.csproj
        arguments: '-c Release'
