resources:
- repo: self
trigger:
  - master
pr:
  - documentation/*

variables:
- template: templates/vars.yml

jobs:
- job: macos_1015
  pool:
    name: Hosted macOS
  steps:
    # setup env
    - task: UseDotNet@2
      displayName: 'Use .Net Core sdk'
      inputs:
        version: $(DOTNET_SDK_VERSION)
    - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
      displayName: Switch to the latest Xamarin SDK
    - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      displayName: Switch to the latest Xcode
    # restore, build
    - script: 'msbuild XToolkit.sln -r /p:Configuration="Release" /p:Platform="Any CPU"'
      displayName: Build Solution
    - bash: 'cd documentation && sh build.sh'
      displayName: Build Documentation
    - task: CopyFiles@2
      inputs:
        contents: 'documentation/_site/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: drop
