resources:
- repo: self
trigger:
  - master
pr:
  paths:
    include:
      - documentation/*

variables:
- template: templates/vars.yml

jobs:
- job: macOS
  pool:
    vmImage: $(MACOS_VM_IMAGE)
  steps:
  - template: templates/setup-dotnet.yml
    parameters:
      version: $(DOTNET_SDK_VERSION)

  - template: templates/setup-xcode.yml
    parameters:
      version: $(XCODE_VERSION)

  - task: DotNetCoreCLI@2
    displayName: Build Solution
    inputs:
      command: build
      configuration: Release
      arguments: --verbosity Detailed

  - bash: 'cd documentation && sh build.sh'
    displayName: Build Documentation

  - task: CopyFiles@2
    inputs:
      contents: 'documentation/_site/**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
