resources:
- repo: self
trigger:
  - release/*
pr: none

queue:
  name: Hosted macOS
  demands: Xamarin.iOS

variables:
  MONO_VERSION: 6_4_0
  BuildConfiguration: 'Release'
  ProjectName: 'Softeq.XToolkit.Permissions'
steps:
  # make sure to select the correct Xamarin and mono
  - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
    displayName: Switch to the latest Xamarin SDK
  - script: 'msbuild nuget/$(ProjectName).sln -r /p:Configuration="$(BuildConfiguration)" /p:Platform="Any CPU"'
  - script: 'nuget pack nuget/$(ProjectName).nuspec'
  - task: CopyFiles@2
    inputs:
      contents: '$(ProjectName)*.nupkg'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'drop'