resources:
- repo: self
trigger:
  - release/*
pr: none

queue:
  name: Hosted macOS
  demands: Xamarin.iOS

variables:
- template: templates/vars.yml

steps:
- template: templates/nuget-symbols-steps.yml
  parameters:
    ProjectName: 'Softeq.XToolkit.Remote'