resources:
- repo: self
queue:
  name: Hosted macOS
  demands: Xamarin.iOS

variables:
  BuildConfiguration: 'Release'
steps:
- script: 'msbuild Softeq.XToolkit.Permissions.sln /t:Clean /p:Configuration="Release" /p:Platform="Any CPU"'
- script: 'nuget restore Softeq.XToolkit.Permissions.sln'
- script: 'msbuild Softeq.XToolkit.Permissions.sln /t:Restore /p:Configuration="Release" /p:Platform="Any CPU"'
- script: 'msbuild Softeq.XToolkit.Permissions.sln /p:Configuration="Release" /p:Platform="Any CPU"'
- script: 'nuget pack Softeq.XToolkit.Permissions.nuspec'
- task: CopyFiles@2
  inputs:
    contents: 'Softeq.XToolkit.Permissions*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'