resources:
- repo: self
trigger:
  - release/*
pr: none

queue:
  name: Hosted macOS
  demands: Xamarin.iOS

steps:
- template: templates/nuget-steps.yml
  parameters:
    ProjectName: 'Softeq.XToolkit.Common'