resources:
- repo: self
trigger:
  branches:
    include:
      - '*'
    exclude:
      - release/*

variables:
- template: templates/vars.yml

jobs:
- template: templates/app-jobs.yml
  parameters:
    SolutionPath: 'samples/Playground/Playground.sln'
    TestsPath: 'Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj'