resources:
- repo: self
trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - documentation/*
  paths:
    include:
      - '*'
    exclude:
      - documentation/*
      - README.md

variables:
- template: templates/vars.yml

jobs:
- template: templates/app-jobs.yml
  parameters:
    SolutionPath: 'XToolkit.sln'