resources:
- repo: self
trigger:
  branches:
    include:
      - '*'
    exclude:
      - release/*
      - documentation/*

variables:
- template: templates/vars.yml

jobs:
- template: templates/app-jobs.yml
  parameters:
    SolutionPath: 'XToolkit.sln'