resources:
- repo: self
trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - documentation/*
      - README.md
# pr: by default runs on each commit (with autoCancel) for all branches

variables:
- template: templates/vars.yml

jobs:
- template: templates/app-jobs.yml
  parameters:
    SolutionPath: 'XToolkit.sln'